apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-reaper
  labels:
    app: boskos-reaper
  namespace: test-pods
spec:
  selector:
    matchLabels:
      app: boskos-reaper
  replicas: 1
  template:
    metadata:
      labels:
        app: boskos-reaper
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos-reaper
        image: quay.io/smuralid/reaper:latest
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --resource-type=vpc-service
