apiVersion: v1
kind: ConfigMap
metadata:
  name: boskos-config
  namespace: test-pods
data:
  boskos-url: "http://boskos.test-pods.svc.cluster.local."
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-ibm
spec:
  provider:
    ibm:
      serviceUrl: "https://f54b9fa4-6cae-4fe1-b1e2-0e49edaa8f14.eu-de.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-cloud-credentials
            key: IBMCLOUD_API_KEY
            namespace: test-pods
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-janitor
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm
    kind: ClusterSecretStore
  target:
    name: boskos-janitor-api-key
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: iam_credentials/c3bd0905-98b2-9cb1-75eb-b666e49c9daf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-janitor-ibmcloud
  namespace: test-pods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boskos-janitor-ibmcloud
  template:
    metadata:
      labels:
        app: boskos-janitor-ibmcloud
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor-ibmcloud
        image: quay.io/smuralid/ibmcloud-janitor-boskos:latest
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --debug
        - --ignore-api-key=true
        env:
        - name: IBMCLOUD_ENV_FILE
          value: "/home/.ibmcloud/key"
        volumeMounts:
        - name: credentials
          mountPath: /home/.ibmcloud
      volumes:
      - name: credentials
        secret:
          secretName: boskos-janitor-api-key
