apiVersion: v1
kind: ConfigMap
metadata:
  name: boskos-config
  namespace: test-pods
data:
  boskos-url: "http://boskos.test-pods.svc.cluster.local."
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-ibm
spec:
  provider:
    ibm:
      serviceUrl: "https://bcc32de5-df5b-467a-b1f7-87d058e6044d.eu-de.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-cloud-credentials
            key: IBMCLOUD_API_KEY
            namespace: test-pods
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-janitor
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm
    kind: ClusterSecretStore
  target:
    name: ibmcloud-janitor-secret
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: 7838e4f2-1cee-8ae3-062f-257e0f4b2471
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-janitor-ibmcloud
  namespace: test-pods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boskos-janitor-ibmcloud
  template:
    metadata:
      labels:
        app: boskos-janitor-ibmcloud
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor-ibmcloud
        image: gcr.io/k8s-staging-boskos/ibmcloud-janitor-boskos:latest
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --debug
        - --ignore-api-key=true
        env:
        - name: IBMCLOUD_ENV_FILE
          value: "/home/.ibmcloud/key"
        volumeMounts:
        - name: credentials
          mountPath: /home/.ibmcloud
      volumes:
      - name: credentials
        secret:
          secretName: ibmcloud-janitor-secret
